import { ExtensionalIR } from "../core/extensional-projector";
import { ConstraintIRBuilder } from "./ir-builder";

export class PromptGenerator {
  public static generateAntiCorruptionPrompt(ir: ExtensionalIR): string {
    const irString = ConstraintIRBuilder.build(ir);
    
    return `### AICA Architecture Boundary Violation

Detected Implicit Coupling. Your code attempts to read an undeclared environment variable or global state, leading to non-confluence under weak memory models.

\`\`\`text
${irString}
\`\`\`

#### Refactoring Directive (Copy to AI assistant):
> System: You are constrained by the AICA Extensionalization protocol.
> Task: Fix the implicit coupling at line ${ir.originalViolation.line}.
> Constraint: ${ir.suggestedAction}
> Action: Elevate this implicit state into an explicit function parameter or injected dependency. Maintain strict purity.

*Auto-generated by AICA Neuro-Symbolic Gatekeeper.*`;
  }
}
